stages:

  - test
  - build
  - deploy



variables:
  IMAGE_NAME: <IP>:5000/nodejs-server-test:$IMAGE_VERSION

cache:
  paths:
    - node_modules/
    
test:
  stage: test
  script:
    - echo 'test'
  tags:
  - cronmonitor

build:
  stage: build
  script:
    - echo 'build'
  tags:
  - cronmonitor

deploy:
  stage: deploy
  script:
    -echo 'deploy'
  tags:
  - cronmonitor


  
