spring:
  profiles:
    group:
      prod: "prod_env,common"
---
spring:
  profiles:
    group:
      dev: "dev_env,common"

---
#운영 환경
spring:
  config:
    activate:
      on-profile: "prod_env"
  redis:
    host: "10.7.27.9"
    port: "6379"
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
#    url: ENC(FT9MAa2OjCi3L4KxLTtuihNe7aaTI+MqU7BqleHlSm37pH/jCsc6kfPLgp0XrR+IhfZvnVMlBz0tsueSbnsMlOC+XgPAUnGAhw8b8BgcqUotG++IpcKRCnqzkJPGp4O3G8CglAb5c18=)
    url: ENC(grsR77SEhN7kmgtfZg7KbctEBHpLc/jA4pLSIrBXErbDc66kd0glUpfwR/4j9SK+91evde+5yCycfYe4wlGJq7tFw2vUm80TjNV+qinr1wP5uJqdx77In475nhw/qy2x)
    username: ENC(vlCqS3V8pcLgDf9i7j4f2Q==)
    password: ENC(zKcrcC7yhJI4oX1N3yIU6ekob3kkHw+T)
  jpa:
    properties:
      hibernate:
        format_sql: true
    hibernate:
#      ddl-auto: create-drop

logging:
  level:
    org.hibernate.SQL: debug
    org.hibernate.type : trace

#jasypt config
jasypt:
  encryptor:
    algorithm: PBEWithMD5AndDES
    bean: jasyptStringEncryptor
    property:
      prefix: ENC(
      suffix: )
    pool-size: 1


server:
  port: 8080
---
#개발 환경
spring:
  config:
    activate:
      on-profile: "dev_env"
  redis:
    host: "182.162.142.151"
    port: "6379"
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: ENC(FT9MAa2OjCi3L4KxLTtuihNe7aaTI+MqU7BqleHlSm37pH/jCsc6kfPLgp0XrR+IhfZvnVMlBz0tsueSbnsMlOC+XgPAUnGAhw8b8BgcqUotG++IpcKRCnqzkJPGp4O3G8CglAb5c18=)
#    url: ENC(grsR77SEhN7kmgtfZg7KbctEBHpLc/jA4pLSIrBXErbDc66kd0glUpfwR/4j9SK+91evde+5yCycfYe4wlGJq7tFw2vUm80TjNV+qinr1wP5uJqdx77In475nhw/qy2x)
    username: ENC(vlCqS3V8pcLgDf9i7j4f2Q==)
    password: ENC(zKcrcC7yhJI4oX1N3yIU6ekob3kkHw+T)
  jpa:
    properties:
      hibernate:
        format_sql: true

server:
  port: 8081
---
#공통환경
spring:
  config:
    activate:
      on-profile: "common"
  jasypt:
    password: "cron_monitoring"
    algorithm: "PBEWithMD5AndDES"
jwt:
  header: Authorization
  secret: 3zWsvEmwL96CJccvPMWhcIMvmK9vKX07dq6J2mRhlMvT5MMVSdl3QR9Hca859z8Wi9EZGWR3rZKj4rIumwHaQQ
  secretRefresh: v-lqiD-sUYSbKirV8DXYxNxX-BidflOsPKhFucu9jk1_qY0vKERn4hbDDaNVviavjliM6TEI92HPADbvAKeIbg
  token-validity-in-seconds: 3600 #1시간
  refresh-token-validity-in-seconds: 1209600 #2주
influx:
  server: http://10.7.27.9:8086/
  token: W90KOru9HsUcsbJ-7NDZvl-ECE5OdsKe3F8LsuNlY5pNQr9mtrE887RnARrNP1Jr6MgE3BACeXptTOkp6E5ibQ==
  org: Gabia
  bucket: Cron